---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Global File Linting
# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lintYaml:
    name: Lint YAML Files
    uses: darpa-askem/orchestration/.github/workflows/lint-yaml.yaml@1938a13230b6e45fc5ea546dcedcc5f2f873a124
    with:
      strict: false

  lintDocker:
    name: Lint Docker Files
    uses: darpa-askem/orchestration/.github/workflows/lint-docker.yaml@1938a13230b6e45fc5ea546dcedcc5f2f873a124
    with:
      failure-threshold: 'error'
